### PR TITLE
COVID botmessage refactor

### PR DESCRIPTION
**Pull request by lucasjcm**
image

See https://github.com/lucasjcm/janule-botmessage-covid

The next step will be to use better data. This is actually using the same data as before. But now we can do our own data processing in https://github.com/lucasjcm/janule-botmessage-covid which I will give you write access to if you want.

Also it demonstrates GitHub Actions which are kind of neat.

### CODE REVIEW

**Comment by bobchen1701** [comment]
tasty beverage

**Comment by lucasjcm** [comment]
https://raw.githubusercontent.com/lucasjcm/janule-botmessage-covid/master/botmessage.txt

That's the message it generates.

**Comment by lucasjcm** [comment]
> tasty beverage

Can you point to the line in the style guide this is based on?

**Comment by lucasjcm** [comment]
Janule nanoservice architecture

**Comment by kmangutov** [comment]
Lgtm

**Review by krishjadhwani — APPROVED** [review]
bananoservice

**Pull request merged**
